name: sonar-repo-scan
on:
  workflow_dispatch:
  push:
jobs:
  sonar-repo-scan:
    uses: bruce-wh-li/security-pipeline-templates/.github/workflows/sonar-scanner.yaml@main
    with:
      ORG: ci-testing
      PROJECT_KEY: secruity_pipeline_templates
      URL: https://sonarqube-59e31e-tools.apps.klab.devops.gov.bc.ca/projects
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
Â© 2022 GitHub, Inc.
Terms
Privacy
Security
